name: Build and Push Container Image

on:
  push:
    branches:
      - test

jobs:
  build-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Podman Build and Push Action
        uses: Frozen-Tapestry/container-action@v1
        with:
          login_registry: ghcr.io
          login_username: ${{ secrets.REGISTRY_USERNAME }}
          login_password: ${{ secrets.REGISTRY_PASSWORD }}
          tags: ghcr.io/EsserGaming/docker-scpsl:latest
          dockerfile: Dockerfile
          # Use those security flags if using GitHub Action. Keep the defaults, if using Gitea.
          security: |
            --security-opt=seccomp=unconfined
            --security-opt=apparmor=unconfined
          push: true
